# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/15d0b22e-decb-4c41-b844-a0f6df0330a2";
      fsType = "btrfs";
      options = [ "compress=zstd,ssd,noatime,space_cache=v2,subvol=nix-root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/15d0b22e-decb-4c41-b844-a0f6df0330a2";
      fsType = "btrfs";
      options = [ "compress=zstd,ssd,noatime,space_cache=v2,subvol=nix-nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/15d0b22e-decb-4c41-b844-a0f6df0330a2";
      fsType = "btrfs";
      options = [ "compress=zstd,ssd,noatime,space_cache=v2,subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8620-32A3";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
